<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>12</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ca.ScottishDwarfStudio.UPooledAudioSystem</RootNamespace>
    </PropertyGroup>

    <ItemGroup>      
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\Unity\Hub\Editor\6000.0.58f2\Editor\Data\Managed\UnityEngine\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\..\..\Unity\Hub\Editor\6000.0.58f2\Editor\Data\Managed\UnityEngine\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\Unity\Hub\Editor\6000.0.58f2\Editor\Data\Managed\UnityEngine\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
    </ItemGroup>
    
    <!-- Make sure unity project actually exists. -->
    <ItemGroup Condition="Exists('..\..\..\Documents\GitHub\DwarfGame\Library\ScriptAssemblies\Assembly-CSharp.dll')">
        <Reference Include="Assembly-CSharp">
            <HintPath>..\..\..\Documents\GitHub\DwarfGame\Library\ScriptAssemblies\Assembly-CSharp.dll</HintPath>
        </Reference>
    </ItemGroup>
    <PropertyGroup Condition="Exists('..\..\..\Documents\GitHub\DwarfGame\Library\ScriptAssemblies\Assembly-CSharp.dll')">
        <DefineConstants>$(DefineConstants);CAN_LINK</DefineConstants>
    </PropertyGroup>
    <ItemGroup Condition="Exists('..\..\..\..\Library\ScriptAssemblies\Assembly-CSharp.dll')">
        <Reference Include="Assembly-CSharp">
            <HintPath>..\..\..\..\Library\ScriptAssemblies\Assembly-CSharp.dll</HintPath>
        </Reference>
    </ItemGroup>
    <PropertyGroup Condition="Exists('..\..\..\..\\Library\ScriptAssemblies\Assembly-CSharp.dll')">
        <DefineConstants>$(DefineConstants);CAN_LINK</DefineConstants>
    </PropertyGroup>
</Project>
